# Generated by Django 4.2.1 on 2023-06-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflix_app_venv', '0002_provincia_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_Profesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Profesion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
    ]
