# Generated by Django 4.2.1 on 2023-06-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflix_app_venv', '0003_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Profesional',
            fields=[
                ('id_Usuario_Profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('foto_perfil', models.CharField(max_length=2083)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('calificacion_obtenida', models.FloatField()),
                ('ciudad_id', models.IntegerField()),
                ('rol_id', models.IntegerField()),
                ('profesion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflix_app_venv.profesion')),
            ],
        ),
    ]
